### ISSUE TITLE
Road animation should be directional

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tron-style#22]
- If it's a oneway road, all animation in one direction (as it is now, but confirm it'll go the "right" direction)
- If it's not a oneway road, then the animation should go 2 directions (like in v1)

**Comment by patriciogonzalezvivo** [comment]
this trick needs some changes on the layer. The oneway yes/no is passed as a 'color:'

Look here: https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/tron.yaml#L37-L43

Then in the shader we interpret the red color as bidirectional:

https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/tron.yaml#L139-L148

**Comment by patriciogonzalezvivo** [comment]
I'm in cross road with this one (see what I just did there ; ) 
To do one/not-one way roads here I need to [add this JS function on the road colors ](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Ffe56f0fe7a648aef18747648f4fb23c4%2Fraw%2F3d9270ea91fc3e8dbb4ea27cc94d4ebabddd9948%2Fscene.yaml&lines=29-35#15.2284/40.6980/-74.0134)

``` YAML
layers:
    roads:
        data: { source: mapzen }
        draw:
            lines:
                order: 2
                width: 5px
                color: |
                    function() { 
                        if (feature.oneway) {
                            return [0.,1.,0.];
                        }
                        return [1.,0.,0.] 
                        }
```

Then in the shader "read" the red channel (or any other) and apply [something like this ](https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/tron.yaml#L139-L148). What's the problem?
Using the color pass data between JS and GLSL, makes the color not useful anymore... it over rides it. That in the old tron was solve by hardcoding the color on the shader. I can do that but first we need to simplify and unify this color transitions, if it's possible to one single color... or (if is not possible) a transition between color A and B using the `function-zoom`:

https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L71
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L210
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L229
https://github.com/tangrams/tron/blob/gh-pages/layers/roads.yaml#L272

Here is an example of how hardcoding all the animated roads between `COLOR_A: vec3(0.418,0.754,0.736)` (for zoom 8) and `COLOR_B: vec3(0.086,0.135,0.260)` (zoom 13) will look like:

https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fb2addb1ee3ab51a6e635f3a7b397aa56%2Fraw%2Fe253d14b7c9ad1bc27ef427d254258426992d8fb%2Fscene.yaml#15.8243/40.7108/-74.0068

@sensescape What do you think? Should I proceed?

**Note**: this should not add to much GPU processing power...
