### ISSUE TITLE
fix Tangram-ES load & draw issues

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tron-style#83]
Tron is failing to load in tangram-ES

```
.706767 - WARNING sceneLoader.cpp:888: Duplicate DataSource: normals-elevation
0.721644 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.722112 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.722299 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.722852 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.726436 - WARNING sceneLoader.cpp:755: Invalid blend mode 'opaque'
0.726580 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.726731 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.726808 - WARNING sceneLoader.cpp:738: 'animated' property will be set but not yet implemented in styles
0.731538 - WARNING styleParam.cpp:144: Unknown StyleParam text:buffer:5px
0.731553 - WARNING styleParam.cpp:144: Unknown StyleParam text:move_into_tile:false
0.731575 - WARNING styleParam.cpp:144: Unknown StyleParam move_into_tile:false
0.732674 - WARNING sceneLoader.cpp:1306: Invalid  'filter':
'{min: 17, area: true}'
Assertion failed: (false), function filterCost, file /Users/patricio/Desktop/paparazzi/tangram-es/core/src/scene/filters.cpp, line 125.
```

`'{min: 17, area: true}'` probably caused by [this line on pois.yaml](https://github.com/tangrams/tron/blob/b7d8bae2e271eb22eca5545062d6f60cb3221479/layers/pois.yaml#L559):

```
           landuse-labels-green-areas-not-national-park:
                filter:
                    all:
                        - area: true
                        - $geometry: point
                        - kind: [park, national_park, "park or protected land", conservation, protected_area, nature_reserve, forest, grass]
                    any:
                        # show labels for smaller landuse areas at higher zooms
                        - { $zoom: [5],    area: { min: 10000000000 } }
                        - { $zoom: [6,7],  area: { min: 5000000000 } }
                        - { $zoom: [8],    area: { min: 1000000000 } }
                        - { $zoom: [9],    area: { min: 100000000 } }
                        - { $zoom: [10],   area: { min: 50000000 } }
                        - { $zoom: [11],   area: { min: 25000000 } }
                        - { $zoom: [12],   area: { min: 5000000 } }
                        - { $zoom: [13],   area: { min: 200000 } }
                        - { $zoom: [14],   area: { min: 50000 } }
                        - { $zoom: [15],   area: { min: 10000 } }
                        - { $zoom: [16],   area: { min: 1000 } }
                        - { $zoom: { min: 17, area: true } }
```

Maybe should be [like this other line](https://github.com/tangrams/tron/blob/b7d8bae2e271eb22eca5545062d6f60cb3221479/layers/pois.yaml#L961)

```
         playgrounds_allotments_attraction_landmark_supermarket:
                filter:
                    all:
                        - kind: [playground, allotments, attraction, landmark, supermarket]
                        - area: true
                        - $geometry: point
                    any:
                        - { $zoom: [15], area: { min: 600 } }
                        - { $zoom: [16], area: { min: 300 } }
                        - { $zoom: { min: 17 }, area: true }
```

Not really sure...

cc @blair1618 @nvkelso @sensescape
